name: civil_manager
description: This app is used to manage construction work status, labour attendance, and payment systems.



publish_to: "" #

version: 2.0.0+13

environment:
  sdk: '>=2.18.4 <3.0.0'



dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: ^10.0.0
  google_fonts: ^4.0.3
  intl:
  json_path: 0.4.1
  page_transition: 2.0.4
  provider: 6.0.4
  shared_preferences: 2.0.15
  sqflite: 2.2.0+2
  styled_divider: 1.0.4
  timeago: 3.2.2
  url_launcher: 6.1.5
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.12.29
  fluttertoast: ^8.1.2
  get: ^4.6.5
  get_storage: ^2.0.3
  android_path_provider: ^0.3.0
  dio: ^4.0.6
  number_to_words_english: ^2.0.2
  icon_badge: ^1.0.0
  easy_rich_text: ^1.1.0
  flutter_neumorphic: ^3.2.0
  flutter_lints: ^2.0.1
  http: ^0.13.5
  camera: ^0.10.3
  image_picker: ^0.8.6+1
  slider_button: ^2.0.0
  flutter_slidable: ^2.0.0
  photo_view: ^0.14.0
  package_info_plus: ^3.0.3
  ftpconnect:
  cool_alert: ^2.0.1
  shimmer:
  syncfusion_flutter_pdfviewer:
  permission_handler: ^10.4.3
  flutter_share_me: ^1.4.0
  syncfusion_flutter_calendar: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/app_launcher_icon.png'


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true


  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/logo/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
